'use strict';
// Classic script: shares the validated solver and unit system with index.html.
const workspacePanel=document.createElement('section');
workspacePanel.className='card workspace-panel';
workspacePanel.innerHTML=`<h2>โครงการและชุดตรวจสอบ</h2><div class="workspace-actions"><label>ชื่อโครงการ<input id="projectName" value="งานวิเคราะห์คาน"></label><button id="projectSave">บันทึกในเครื่อง</button><select id="projectList" aria-label="โครงการที่บันทึก"></select><button id="projectOpen">เปิดงาน</button><button id="projectExport">ส่งออกโครงการ</button><label class="file-button">นำเข้าโครงการ<input id="projectImport" type="file" accept=".json,application/json"></label></div><p id="workspaceMessage" role="status"></p><details><summary>โจทย์อ้างอิงจากเอกสาร</summary><select id="referenceList" aria-label="เลือกโจทย์อ้างอิง"></select><button id="referenceOpen">เปิดโจทย์</button><p id="referenceNote"></p></details><details><summary>หลายกรณีแรงและค่าครอบคลุม</summary><p>กำหนดตัวคูณแยกแต่ละแรง P = แรงจุด, W = แรงกระจาย, M = โมเมนต์ เรียงตามรายการในชนิดนั้น แรงที่ไม่ได้ระบุใช้ตัวคูณ 1 ตัวคูณเหล่านี้เป็นค่าที่ผู้ใช้กำหนด</p><textarea id="caseInput" rows="4" aria-label="กรณีแรง">ใช้งาน: P1=1,W1=1\nเพิ่มแรง: P1=1.5,W1=1.2</textarea><button id="caseRun">ตรวจทุกกรณี</button><div id="caseOutput"></div></details><button id="reportBuild">จัดทำรายงาน</button><button id="reportPrint" hidden>พิมพ์ / บันทึก PDF</button><div id="reportPreview"></div></section>`;
document.querySelector('main').append(workspacePanel);
const ws=id=>document.getElementById(id),message=text=>ws('workspaceMessage').textContent=text;
const storageKey='hrtx-beam-projects-v1';
function savedProjects(){const data=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(data))throw Error('ข้อมูลบันทึกไม่ถูกต้อง');return data;}
function refreshProjects(){try{ws('projectList').replaceChildren(...savedProjects().map((p,i)=>new Option(p.meta.name,String(i))));}catch(e){message('เปิดพื้นที่บันทึกไม่ได้: '+e.message);}}
function projectSnapshot(){const settings={};document.querySelectorAll('#tab-1 input[id],#tab-1 select[id],#tab-1 textarea[id],#matCard input[id],#matCard select[id],#matCard textarea[id],#ltbConfig input[id],#ltbConfig select[id]').forEach(e=>{if(!e.closest('.item')&&e.type!=='file')settings[e.id]={value:e.value,checked:e.checked};});return {schema:'hrtx-beam-project',version:1,meta:{name:ws('projectName').value.trim()||'งานวิเคราะห์คาน',beamType:curType,savedAt:new Date().toISOString()},units:{...UNIT},model:readInputs(),settings,radios:Object.fromEntries(Array.from(document.querySelectorAll('#tab-1 input[type=radio]:checked,#matCard input[type=radio]:checked')).map(e=>[e.name,e.value]))};}
function checkProject(p){if(!p||p.schema!=='hrtx-beam-project'||p.version!==1||!p.meta||typeof p.meta.name!=='string'||p.meta.name.length>200||!p.settings||typeof p.settings!=='object'||!p.units||!['N','kN','lb','kip'].includes(p.units.F)||!['m','in'].includes(p.units.L))throw Error('รูปแบบไฟล์โครงการไม่ถูกต้อง');if((p.units.L==='in')!==['lb','kip'].includes(p.units.F))throw Error('หน่วยโครงการไม่สอดคล้องกัน');const errors=validateModel(p.model);if(errors.length)throw Error(errors.join(' · '));return p;}
function restoreProject(p){checkProject(p);clearWorkspaceResults();coherentUnits(p.units.L==='in'?'US':'SI',p.units.F);const m=p.model,div=p.units.L==='in'?12:1;ws('L').value=m.L/div;ws('sups').replaceChildren();ws('loads').replaceChildren();m.sups.forEach(s=>{addSup(s.t,s.x/div);ws('sups').lastElementChild.querySelector('[data-k="angle"]').value=s.angle||90;});m.points.forEach(q=>addPoint(q.x/div,Math.abs(q.F),q.F<0?-1:1));m.dists.forEach(q=>addDist(q.s/div,q.e/div,q.w1*div,q.w2*div,1));m.moms.forEach(q=>addMom(q.x/div,Math.abs(q.C)/div,q.C<0?-1:1));const apply=()=>Object.entries(p.settings).forEach(([id,v])=>{const e=ws(id);if(e&&!e.closest('.item')&&e.matches('#tab-1 input,#tab-1 select,#tab-1 textarea,#matCard input,#matCard select,#matCard textarea,#ltbConfig input,#ltbConfig select')&&!['L','uF','uL','unitSystem','ltbConfirm'].includes(id)&&v&&typeof v.value==='string'){if(e.tagName==='SELECT'&&!Array.from(e.options).some(o=>o.value===v.value))return;e.value=v.value;if(e.type==='checkbox'||e.type==='radio')e.checked=!!v.checked;}});if(p.radios)document.querySelectorAll('#tab-1 input[type=radio],#matCard input[type=radio]').forEach(e=>{if(typeof p.radios[e.name]==='string')e.checked=e.value===p.radios[e.name];});apply();syncSec();syncSpecificSection();apply();syncStressMode();syncElasticFields();applyUnits();invalidate();preview();curType=p.meta.beamType||'custom';markType();ws('projectName').value=p.meta.name;if(ws('ltbConfirm'))ws('ltbConfirm').checked=false;switchTab(1);message('เปิดโครงการแล้ว กรุณาวิเคราะห์เพื่อสร้างผลใหม่');}
ws('projectSave').onclick=()=>{try{const p=checkProject(projectSnapshot()),all=savedProjects(),i=all.findIndex(q=>q.meta.name===p.meta.name);if(i>=0)all[i]=p;else all.push(p);localStorage.setItem(storageKey,JSON.stringify(all));refreshProjects();message('บันทึกแล้วในเบราว์เซอร์นี้ ควรส่งออกไฟล์เพื่อสำรองงาน');}catch(e){message(e.message);}};
ws('projectOpen').onclick=()=>{try{restoreProject(savedProjects()[Number(ws('projectList').value)]);}catch(e){message(e.message);}};
ws('projectExport').onclick=()=>{try{downloadText('hrtx-beam-project.json',JSON.stringify(checkProject(projectSnapshot()),null,2),'application/json');message('ส่งออกโครงการแล้ว');}catch(e){message(e.message);}};
ws('projectImport').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('ไฟล์ต้องไม่เกิน 2 MB');restoreProject(checkProject(JSON.parse(await f.text())));}catch(err){message('นำเข้าไม่ได้: '+err.message);}finally{e.target.value='';}};
const referenceModels=[
 {name:'EX — คาน 5 m',source:'EX Deflection calculation หน้า 1, 8–9; ตรวจค่าเฉลยด้วยเงื่อนไขขอบใหม่',L:5,s:[["pin",0],["roller",5]],p:[[4,50]],w:[[0,3,20,20]],expected:'ปฏิกิริยา 52 / 58 kN; |M|max 67.6 kN·m; E 200 GPa, I 12100 cm⁴ ให้ |δ|max ≈ 7.47751 mm ที่ x ≈ 2.54565 m',elastic:true},
 {name:'Q4 — คานยื่นและแรงกระจาย',source:'Q4 Stress in beam (Mon) หน้า 1–2; ไม่รวมน้ำหนักคาน',L:6,s:[["pin",1.5],["roller",6]],p:[[0,40]],w:[[4,6,45,45]],expected:'ปฏิกิริยา 73.3333 / 56.6667 kN; |M|max 60 kN·m'},
 {name:'Final 1 — ข้อ 1 สายเคเบิล',source:'Final test mechnaics of materials 1 -2568 หน้า 1; α = atan2(3,−4); ค่านี้ยังไม่รวมน้ำหนักคาน',L:4,s:[["pin",0],["cable",4,143.130102354156]],p:[[2,.5]],w:[[0,2,.25,.25]],expected:'แรงแนวดิ่ง 0.625 / 0.375 kN; T = 0.625 kN; N = −0.5 kN'},
 {name:'Final 1 — ข้อ 2 คานยึดแน่น',source:'Final test mechnaics of materials 1 -2568 หน้า 2; ไม่รวมน้ำหนักคาน',L:4.5,s:[["fixed",0]],w:[[0,3,2,2],[3,4.5,4,0]],expected:'แรงรองรับ 9 kN; โมเมนต์รองรับ 19.5 kN·m'},
 {name:'Final 2 — ข้อ 1 โมเมนต์ที่ปลาย',source:'Final test mechnaics of materials 2 -2568 หน้า 1; คู่ควบทวนเข็ม 40 kN·m',L:4.8,s:[["pin",0],["roller",4.8]],w:[[1.6,4.8,25,25]],m:[[0,-40]],expected:'ปฏิกิริยา 35 / 45 kN; |M|max 40.5 kN·m'},
 {name:'Final 2 — ข้อ 2 ยึดแน่นด้านขวา',source:'Final test mechnaics of materials 2 -2568 หน้า 2; E ต้องกำหนดเพิ่มเติม',L:4,s:[["fixed",4]],p:[[0,2]],w:[[2,4,1.5,1.5]],expected:'แรงรองรับ 5 kN; |M|max 11 kN·m'},
 {name:'Practice 5.14 — คานหน้าตัดสี่เหลี่ยม',source:'Practice C5-1 หน้า 3; หน้าตัด 120 × 400 mm, ความเค้นดัดยอมให้ 10 MPa',L:5,s:[["pin",0],["roller",5]],p:[[4,32.5]],w:[[0,5,3,3]],expected:'ที่ P = 32.5 kN ให้ |M|max 32 kN·m และ σmax = 10 MPa'},
 {name:'Practice 5.46 — แรงกระจายเต็มช่วง',source:'Practice C5-2 หน้า 1; ความเค้นดัดยอมให้ 120 MPa',L:8,s:[["pin",0],["roller",8]],w:[[0,8,12,12]],expected:'|M|max 96 kN·m; ตาราง APP ให้ W460×52 มี σ ≈ 106 MPa'},
 {name:'Chapter 4 — แรงกระจายแยกช่วง',source:'Chapter 4 Shear and moment in beam หน้า 57',L:6,s:[["pin",0],["roller",6]],w:[[0,2,50,50],[4,6,20,20]],expected:'ปฏิกิริยา 90 / 50 kN; |M|max 81 kN·m ที่ x = 1.8 m'}
];
ws('referenceList').replaceChildren(...referenceModels.map((r,i)=>new Option(r.name,String(i))));
ws('referenceOpen').onclick=()=>{try{const r=referenceModels[Number(ws('referenceList').value)];restoreProject({schema:'hrtx-beam-project',version:1,meta:{name:r.name},units:{F:'kN',L:'m'},settings:{},model:{L:r.L,sups:r.s.map(([t,x,angle])=>({t,x,angle})),points:(r.p||[]).map(([x,F])=>({x,F})),dists:(r.w||[]).map(([s,e,w1,w2])=>({s,e,w1,w2})),moms:(r.m||[]).map(([x,C])=>({x,C}))}});ws('defEnabled').checked=!!r.elastic;ws('courseSelfWeight').checked=false;ws('caseInput').value='ใช้งาน: '+[...r.p?r.p.map((_,i)=>'P'+(i+1)+'=1'):[],...r.w?r.w.map((_,i)=>'W'+(i+1)+'=1'):[],...r.m?r.m.map((_,i)=>'M'+(i+1)+'=1'):[]].join(',');if(r.elastic){ws('defE').value=200;ws('defEu').value='GPa';ws('defI').value=12100;ws('defIu').value='cm4';}syncElasticFields();ws('referenceNote').textContent=r.source+' · '+r.expected;message('เปิดโจทย์แล้ว ค่าหน้าตัดและเกณฑ์ออกแบบอื่นต้องกำหนดตามโจทย์');}catch(e){message(e.message);}};
function loadCases(text,model){const keys=[...model.points.map((_,i)=>'P'+(i+1)),...model.dists.map((_,i)=>'W'+(i+1)),...model.moms.map((_,i)=>'M'+(i+1))];const lines=text.split(/\n/).filter(s=>s.trim());if(!lines.length||lines.length>30)throw Error('กำหนด 1–30 กรณี');return lines.map(line=>{const at=line.indexOf(':');if(at<1)throw Error('ใช้รูปแบบ ชื่อกรณี: P1=1,W1=1');const factors={};for(const term of line.slice(at+1).split(',').filter(s=>s.trim())){const match=term.trim().match(/^([PWM]\d+)\s*=\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)$/i);if(!match||!keys.includes(match[1].toUpperCase()))throw Error('รายการแรงไม่ถูกต้อง: '+term);const key=match[1].toUpperCase(),v=Number(match[2]);if(!Number.isFinite(v)||Math.abs(v)>100||key in factors)throw Error('ตัวคูณซ้ำหรืออยู่นอกช่วง ±100');factors[key]=v;}const m=JSON.parse(JSON.stringify(model));[['points','P','F'],['moms','M','C']].forEach(([list,p,k])=>m[list].forEach((q,i)=>q[k]*=factors[p+(i+1)]??1));m.dists.forEach((q,i)=>{const f=factors['W'+(i+1)]??1;q.w1*=f;q.w2*=f;q.w1_in=q.w1;q.w2_in=q.w2;});return {name:line.slice(0,at).trim(),model:m};});}
ws('caseRun').onclick=()=>{try{const model=readInputs(),errors=validateModel(model),elastic=readElastic();if(errors.length||elastic.errors.length)throw Error([...errors,...elastic.errors].join(' · '));const cases=loadCases(ws('caseInput').value,model).map(c=>{const r=analyze(c.model);if(r.unstable)throw Error(c.name+': คานไม่เสถียร');const d=elastic.mat?computeDeflection(r,c.model,elastic.mat):null;return {...c,r,d};});const envelope=k=>cases.reduce((a,c)=>k(c)>k(a)?c:a);ws('caseOutput').innerHTML='<p>ค่าครอบคลุม |V|: '+esc(envelope(c=>c.r.Vmax.abs).name)+' · |M|: '+esc(envelope(c=>c.r.Mabs.abs).name)+(elastic.mat?' · |δ|: '+esc(envelope(c=>c.d.max.abs).name):'')+'</p><table><thead><tr><th>กรณี</th><th>|V|max ('+esc(UNIT.F)+')</th><th>|M|max ('+esc(UNIT.F+'·'+UNIT.L)+')</th><th>|δ|max</th><th>สมดุล</th></tr></thead><tbody>'+cases.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+fmt(c.r.Vmax.abs)+'</td><td>'+fmt(c.r.Mabs.abs)+'</td><td>'+(c.d?fmt(defValue(c.d.max.abs))+' '+defUnit():'ไม่ได้ตรวจ')+'</td><td>'+(c.r.accuracy.ok?'ผ่าน':'ไม่ผ่าน')+'</td></tr>').join('')+'</tbody></table><p>ตรวจโมเดลที่กรอกโดยตรง ยังไม่เพิ่มน้ำหนักหน้าตัดอัตโนมัติในชุดกรณีแรง</p>';message('ตรวจครบ '+cases.length+' กรณี');}catch(e){ws('caseOutput').textContent=e.message;}};
ws('reportBuild').onclick=()=>{if(!last){message('วิเคราะห์คานก่อนจัดทำรายงาน');return;}const section=document.createElement('article');section.id='hrtxReport';const h=document.createElement('h1');h.textContent='HRTX / beam — '+ws('projectName').value;section.append(h);const note=document.createElement('p');note.textContent='รายงาน ณ '+new Date().toLocaleString('th-TH')+' · หน่วย '+UNIT.F+' / '+UNIT.L+' · คานเชิงเส้น ยืดหยุ่น หน้าตัดคงที่ และการโก่งตัวขนาดเล็ก';section.append(note);const inputs=document.createElement('pre');inputs.textContent=JSON.stringify(last.inp,null,2);const detail=document.createElement('details');detail.innerHTML='<summary>ข้อมูลคานที่ใช้คำนวณ</summary>';detail.append(inputs);section.append(detail);for(const id of ['ans','fig','analysisChecks','deflectionReport','dans','designChecks','advancedOutput']){const original=ws(id);if(!original||original.hidden||id==='dans'&&!last.design||id==='designChecks'&&!last.design)continue;const clone=original.cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));clone.querySelectorAll('button,input,select').forEach(e=>e.remove());section.append(clone);}const limits=document.createElement('p');limits.textContent='ผลผ่านหมายถึงผ่านเฉพาะรายการและเกณฑ์ที่แสดงในรายงาน ต้องตรวจเสถียรภาพด้านข้าง จุดต่อ ความล้า และข้อกำหนดโครงการเพิ่มเติมเมื่อเกี่ยวข้อง';section.append(limits);ws('reportPreview').replaceChildren(section);ws('reportPrint').hidden=false;message('รายงานพร้อมตรวจทาน เลือกพิมพ์และบันทึกเป็น PDF ในเบราว์เซอร์');};
ws('reportPrint').onclick=()=>{ws('hrtxPrint')?.remove();const copy=ws('hrtxReport').cloneNode(true);copy.id='hrtxPrint';copy.querySelectorAll('details').forEach(e=>e.open=true);document.body.append(copy);document.body.classList.add('print-report');window.print();};window.addEventListener('afterprint',()=>{document.body.classList.remove('print-report');ws('hrtxPrint')?.remove();});
refreshProjects();

function clearWorkspaceResults(){ws('reportPreview').replaceChildren();ws('reportPrint').hidden=true;ws('caseOutput').replaceChildren();}
document.addEventListener('input',e=>{if(e.target.closest('#tab-1,#matCard,#ltbConfig'))clearWorkspaceResults();});document.addEventListener('change',e=>{if(e.target.closest('#tab-1,#matCard,#ltbConfig'))clearWorkspaceResults();});

